routes/web.php
<?php

use App\Models\Content;
use Illuminate\Support\Facades\Route;



Auth::routes();



Route::group([
   'prefix' => 'admin',
   'as' => 'backend.',
   'middleware' => 'auth',
], function () {
   Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
   Route::get('/dashboard', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
   Route::resource('timeline', App\Http\Controllers\Backend\TimelineController::class);

   //POST ROUTE
   Route::group([
      'prefix' => 'post',
      'as' => 'post.',
   ], function () {
      Route::resource('content', App\Http\Controllers\Backend\Post\ContentController::class);
      Route::get('content/getimage/{id}', [App\Http\Controllers\Backend\Post\ContentController::class, 'getImage']);
      Route::post('content/addimage', [App\Http\Controllers\Backend\Post\ContentController::class, 'addImage'])->name('addimage');
      Route::delete('content/deleteimage/{id}', [App\Http\Controllers\Backend\Post\ContentController::class, 'deleteImage'])->name('deleteimage');
      Route::post('content/edit/editimage', [App\Http\Controllers\Backend\Post\ContentController::class, 'editImage'])->name('editimage');
      Route::resource('category', App\Http\Controllers\Backend\Post\CategoryController::class);
      Route::resource('tag', App\Http\Controllers\Backend\Post\TagController::class);
   });

   Route::resource('slider', App\Http\Controllers\Backend\SliderController::class);
   //about
   Route::group([
      'prefix' => 'about',
      'as' => 'about.',
   ], function () {
      Route::resource('structure', App\Http\Controllers\Backend\About\StructureController::class);
      Route::resource('contact', App\Http\Controllers\Backend\About\ContactController::class);


      Route::resource('member', App\Http\Controllers\Backend\About\MemberController::class);
   });
});

app/Models/Content.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Content extends Model
{
    use HasFactory;

    protected $guarded = [''];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }
    public function tags()
    {
        return $this->belongsToMany(Tag::class);
    }

    public function files()
    {
        return $this->morphMany(File::class, 'fileable');
    }
}

app/Http/Controllers/Api/ContentController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Resources\ContentResource;
use App\Models\Category;
use Illuminate\Http\Request;
use App\Models\Content;
use Spatie\QueryBuilder\QueryBuilder;

class ContentController extends Controller
{
   public function index()
   {
      $query = Content::latest();
      $content = QueryBuilder::for($query)
         ->allowedFilters('title')
         ->paginate(5);
      ContentResource::collection($content);
      return response()->json(
         [
            "data" => $content,
            "status" => 201
         ]
      );
   }

   public function indexByCategory($slug)
   {
      $data = Category::where('slug', $slug)->first();

      if ($data == null) {
         return response()->json(
            [
               "status" => 404
            ]
         );
      }
      $query = Content::where('category_id', $data->id);
      $content = QueryBuilder::for($query)
         ->paginate(5);
      ContentResource::collection($content);
      return response()->json(
         [
            "data" => $content,
            "status" => 201
         ]
      );
   }

   public function indexCategory()
   {
      $query = Category::latest();
      $category = QueryBuilder::for($query)
         ->allowedFilters('title')
         ->paginate(5);
      return response()->json(
         [
            "data" => $category,
            "status" => 201
         ]
      );
   }

   public function show($slug)
   {
      $query = Content::where('slug', $slug);
      $content = QueryBuilder::for($query)
         ->firstOrFail();
      return response()->json(
         [
            "data" => $content,
            "status" => 201
         ]
      );
   }
}

app/Http/Controllers/Backend/Post/CategoryController.php
<?php

namespace App\Http\Controllers\Backend\Post;

use App\Http\Controllers\Controller;
use App\Models\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Yajra\DataTables\Facades\DataTables;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

        if ($request->ajax()) {
            $categories = Category::latest()->get();
            return DataTables::of($categories)
                ->addColumn('action', function ($category) {
                    return '
                             <a class="btn btn-danger btn-sm"  onclick="deleteItem(' . $category->id . ')"><i class="fa fa-trash"></i></span></a>
                             <a class="btn btn-info btn-sm" onclick="editItem(' . $category->id . ')"><i class="fa fa-pencil"></i></span></a>
                             ';
                })
                ->removeColumn('id')
                ->addIndexColumn()
                ->rawColumns(['action'])
                ->make(true);
        }
        $data['title'] = "CATEGORY";
        return view('backend.post.category.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $category = new Category();
        $category->name = $request->name;
        $category->slug = Str::of($request->name)->slug('-');
        // dd($category->slug);
        $category->save();
        return $category;

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return $category;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {

        $category->update($request->all());
        $category->slug = Str::of($request->name)->slug('-');
        $category->save();
        return $category;

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $category->delete();
        return response()->json(['message', 'deleted success']);

    }
}

app/Http/Controllers/Backend/Post/ContentController.php
<?php

namespace App\Http\Controllers\Backend\Post;

use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Content;
use App\Models\File;
use App\Models\Tag;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Facades\Image as Img;
use Str;
use Yajra\DataTables\Facades\DataTables;

class ContentController extends Controller
{
   /**
    * Display a listing of the resource.
    *
    * @return \Illuminate\Http\Response
    */
   public function index(Request $request)
   {

      if ($request->ajax()) {
         $contents = Content::latest()->get();
         return DataTables::of($contents)
            ->addColumn('category', function ($item) {
               return $item->category->name;
            })
            ->addColumn('tag', function ($item) {
               $name = "";
               $tag = $item->tags->map(function ($data) {
                  return $data->name;
               });
               if (count($tag) > 0) {
                  for ($i = 0; $i < count($tag); $i++) {
                     $name = $name . $tag[$i] . ", ";
                  }
               } else {
                  $name = "-";
               }

               return $name;
            })
            ->addColumn('action', function ($content) {
               return '

                             <a class="btn btn-danger btn-sm"  onclick="deleteItem(' . $content->id . ')"><i class="fa fa-trash"></i></span></a>
                             <a class="btn btn-info btn-sm" onclick="editItem(' . $content->id . ')"><i class="fa fa-pencil"></i></span></a>
                             ';
            })
            ->addColumn('status', function ($content) {
               if ($content->status == true) {
                  return '
                           <p class="btn btn-success btn-trans btn-sm" >Published</span></a>
                        ';
               } else {
                  return '
                     <p class="btn btn-warning btn-trans btn-sm" >Draft</span></a>
                        ';
               }
            })
            ->removeColumn('id')
            ->addIndexColumn()
            ->rawColumns(['action', 'status'])
            ->make(true);
      }
      $data['title'] = "CONTENT";

      return view('backend.post.content.index', $data);
   }

   /**
    * Show the form for creating a new resource.
    *
    * @return \Illuminate\Http\Response
    */
   public function create()
   {
      $data['title'] = "CONTENT > CREATE";
      $data['tags'] = Tag::all();
      $data['categories'] = Category::all();
      return view('backend.post.content.create', $data);
   }

   /**
    * Store a newly created resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @return \Illuminate\Http\Response
    */
   public function store(Request $request)
   {
      //   dd($request->all());
      $path = null;
      if ($request->id != 0) {
         $content = Content::find($request->id);
         $content->tags()->detach();
         $content->update($request->except('image', 'tag'));
         $content->tags()->attach($request->tag);
         $content->slug = Str::of($request->title)->slug('-');
         $content->created_at = Carbon::now();
         $content->save();
         return redirect(route('backend.post.content.index'))->with([
            'type' => 'success',
            'toast' => 'Content successfully Published',
         ]);
      }
      DB::transaction(function () use ($request) {

         $slug = Str::slug($request->title, '-');

         $request->request->add([
            'slug' => $slug,
         ]);
         $item = Content::create($request->except('image', 'tag'));
         $item->tags()->attach($request->tag);
      });

      return redirect(route('backend.post.content.index'))->with([
         'type' => 'success',
         'toast' => 'Content successfully Created',
      ]);
   }

   /**
    * Display the specified resource.
    *
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
   public function show($id)
   {
      //
   }

   /**
    * Show the form for editing the specified resource.
    *
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
   public function edit(Content $content)
   {
      //   dd("masuk")
      $data['title'] = "CONTENT > EDIT";
      $data['content'] = $content;
      $data['categories'] = Category::all();
      $data['tags'] = Tag::all();
      return view('backend.post.content.edit', $data);
   }

   /**
    * Update the specified resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
   public function update(Request $request, $id)
   {
      $path = null;

      if ($id == 0) {
         $slug = Str::slug($request->title, '-') . time();

         $request->request->add([
            'slug' => $slug,
         ]);

         $item = Content::create($request->except('image', 'tag'));
         $item->tags()->attach($request->tag);
      } else {
         $content = Content::find($id);
         $content->tags()->detach();
         $content->update($request->except('image', 'tag'));
         $content->slug = Str::of($request->title)->slug('-');
         $content->tags()->attach($request->tag);
         $content->save();
         $item = $content;
      }

      //   dd($request->title);
      return response()->json([
         $item,
      ]);
   }

   /**
    * Remove the specified resource from storage.
    *
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
   public function destroy(Content $content)
   {
      $content->tags()->detach();
      foreach ($content->files as $key => $image) {
         // dd($image->link);
         if (Storage::exists("public/" . $image->link)) {
            Storage::delete("public/" . $image->link);
            $image->delete();
         }
      }

      $content->delete();

      return response()->json(['message', 'deleted success']);
   }
   public function getImage($id)
   {
      $file = File::where('fileable_id', $id)->where('fileable_type', 'App\Models\Content')->get();
      return response()->json($file, 200);
   }

   public function editImage(Request $request)
   {
      $content = Content::find($request->content);
      //   dd($content->images);
      $path = null;
      if ($request->file('image')) {
         foreach ($request->file('image') as $key => $image) {
            $img = $content->files[$key];
            //  dd($img);

            $name_picture = Str::random(6) . '.png';
            $picture = Img::make($image)->resize(null, 1000, function ($constraint) {
               $constraint->aspectRatio();
               $constraint->upsize();
            })->encode('png', 100);
            if (Storage::exists("public/" . $img->link)) {
               Storage::delete("public/" . $img->link);
               $img->delete();
            }
            $namePath = strtolower(Category::find($content->category_id)->name);
            $path = $namePath . "/" . $name_picture;

            Storage::put("public/" . $path, $picture);
            // dd(Storage::exists($content->images));

            if ($path != null) {
               $content->files()->create(['link' => $path, 'type' => 'image']);
            }
            //  dd($content->images);
         }
      } else {
         $data['message'] = "No Image Changed";
         return response()->json($data);
      }

      $data['message'] = "Image Has Been Changed";
      //   $data['part_id'] = $gambar_part->part_id;
      return response()->json($data, 200);
   }

   public function addImage(Request $request)
   {

      $content = Content::find($request->content);
      //   dd($request->content);
      $path = null;

      if ($request->file('image')) {
         $name_picture = Str::random(6) . '.png';
         $picture = Img::make($request['image'])->resize(null, 1000, function ($constraint) {
            $constraint->aspectRatio();
            $constraint->upsize();
         })->encode('png', 100);
         $namePath = strtolower(Category::find($content->category_id)->name);
         $path = $namePath . "/" . $name_picture;

         Storage::put("public/" . $path, $picture);
         // dd(Storage::exists($content->images));
      }
      if ($path != null) {
         $content->files()->create(['link' => $path, 'type' => 'image']);
      }
      //   dd($content->files);

      return response()->json(200);
   }

   public function deleteImage($id)
   {
      if ($id != "") {
         $img = File::find($id);
         if ($img->link != null) {
            if (Storage::exists("public/" . $img->link)) {
               Storage::delete("public/" . $img->link);
               $img->delete();
            }
         }
         return response()->json('success', 200);
      }
      return "gagal";
   }
}

resources/views/backend/post/content/_form.blade.php
@extends('backend.crud.modal')
@section('input-form')
<div class="form-group">
   <div class="form-line">
      <label for="name">Nama Produk</label>
      <input type="text" name="name" class="form-control" minlength="5" required>
   </div>
</div>

{{-- <div class="form-group">
    <div class="form-line">
        <label for="number">Gambar Produk</label>
        <input type="text" name="name" class="form-control">
    </div>
</div> --}}

{{-- <div class="form-group">
   <label for="type">Pilih Salah Satu</label>
   <select class="form-control show-tick" name="type_id" id="typeID" required>
      <option disabled selected value>---- Pilih Salah Satu ----</option>
      @foreach ($type as $item)
      <option value="{!! $item->id !!}">{!! $item->name !!}</option>
      @endforeach
   </select>
</div> --}}

@endsection

resources/views/backend/post/content/_image.blade.php
<script>
   $("body").on("submit", "#formItemImage", function (event) {
      event.preventDefault()
      Swal.fire({
         type: 'warning',
    text: 'Please wait.',
    showCancelButton: false,
    confirmButtonText: "ok",
    allowOutsideClick: false,
    allowEscapeKey: false
      })
      Swal.showLoading()

      let content = id;
      if (typeof content === "undefined") {
         alert('no image for changed');
         location.reload();
      }
      let dataKu = new FormData(this)
      dataKu.append('content', id)

      $.ajax({
         type: "POST",
         enctype: "multipart/form-data",
         url: "{{ route('backend.post.editimage')  }}",
         headers: {
            'X-CSRF-TOKEN': "{{ csrf_token()  }}"
         },
         data: dataKu,
         processData: false,
         contentType: false,
         cache: false,
         xhr: function () {
            var xhr = $.ajaxSettings.xhr();
            xhr.upload.onprogress = function (e) {
               // For uploads

            };
            return xhr;
         },

         success: function (response) {
            // console.log(response)

            // $(".childEl").empty()

            Swal.fire({
               position: 'top-end',
               icon: 'success',
               title: response.message,
               showConfirmButton: false,
               timer: 1500
            })
            getImage(window.imageID)
            // setTimeout(function () {
            //    location.reload();
            // }, 2500);
         },
         error: function (xhr, status, error) {
            $(".childEl").empty()
            swallFire('error', JSON.parse(xhr.responseText))
         }
      })
   })

   $("body").on("submit", "#formAddItemImages", function (event) {
      event.preventDefault()
      Swal.fire({
         type: 'warning',
    text: 'Please wait.',
    showCancelButton: false,
    confirmButtonText: "ok",
    allowOutsideClick: false,
    allowEscapeKey: false
      })
      Swal.showLoading()
      // console.log("masuk")
      let dataKu = new FormData(this)
      dataKu.append('content', window.imageID)


      // console.log("data : "+dataKu)

      $.ajax({
         type: "POST",
         enctype: "multipart/form-data",
         url: "{{ route('backend.post.addimage')  }}",
         headers: {
            'X-CSRF-TOKEN': "{{ csrf_token()  }}"
         },
         data: dataKu,
         processData: false,
         contentType: false,
         cache: false,


         success: function (response) {
            $(".childEl").empty()

            $('#imgAdd').val('')

            Swal.fire({
               position: 'top-end',
               icon: 'success',
               title: 'Your Image has been saved',
               showConfirmButton: false,
               timer: 1500
            })
            getImage(window.imageID)
         },
         error: function (xhr, status, error) {
            $(".childEl").empty()
            swallFire('error', JSON.parse(xhr.responseText))
         }
      })
   })

   function getImage(id) {
      $.get("{{ url('/admin/post/content/getimage')  }}" + "/" + id, function (data) {
         // console.log('masuk')
         
         $('.table-item-image .tbody').empty();
         $.each(data, function (i, item) {
            console.log(item.link);
            $('.table-item-image .tbody').append(`
                            <tr>
                                <td>${i+1}</td>
                                <td><img src="/storage/${item.link}" style="max-height:100px"></td>
                                <td>
                                    <span class="input_hidden"></span>
                                    <input id="image" type="file" class="form-control image" name="image[]" data-id="${item.id}"/>
                                </td>
                                <td><button type="button" data-id="${item.id}" class="btn btn-xs btn-danger delItemImage">Hapus</button></td>
                            </tr>
                        `);
         });
      })
   }

   $("#btnAddImage").on("click", function () {
      // console.log('masuuk')
      $("#modalItemImages").modal('show')


      window.imageID = id
      getImage(window.imageID)
   })
   $("body").on("click", ".delItemImage", function (e) {
      e.preventDefault()
      Swal.fire({
         type: 'warning',
    text: 'Please wait.',
    showCancelButton: false,
    confirmButtonText: "ok",
    allowOutsideClick: false,
    allowEscapeKey: false
      })
      Swal.showLoading()
      let img = $(this).data("id")
      // console.log("masuk" + id)

      Swal.fire({
         title: 'Are you sure?',
         text: "You won't be able to revert this!",
         type: 'warning',
         showCancelButton: true,
         confirmButtonColor: '#3085d6',
         cancelButtonColor: '#d33',
         confirmButtonText: 'Yes, delete it!'
      }).then((result) => {
         // console.log(result.value)

         if (result.value) {

            $.post("/admin/post/content/deleteimage" + "/" + img, {
                  '_method': "DELETE",
                  "_token": "{{ csrf_token()  }}"
               })
               .done(function (response) {
                  Swal.fire({
                     position: 'top-end',
                     icon: 'success',
                     title: 'Your Image has been deleted',
                     showConfirmButton: false,
                     timer: 1500
                  })
                  getImage(window.imageID);
               })
               .fail(function (error) {
                  swallFire("error", error)
               })
         }
      })
   })

   function swallFire(type, message) {
      Swal.fire({
         position: 'center',
         text: message,
         type: type,
         showConfirmButton: false,
         timer: 1500
      })
   }

</script>

resources/views/backend/post/content/index.blade.php
@extends('layouts.backend')

@section('title','Dashboard')

@push('css')
<link href="{{ asset('assets/plugins/datatables/dataTables.bootstrap4.min.css')  }}" rel="stylesheet" type="text/css" />
<link href="{{ asset('assets/plugins/datatables/buttons.bootstrap4.min.css')  }}" rel="stylesheet" type="text/css" />
<!-- Responsive datatable examples -->
<link href="{{ asset('assets/plugins/datatables/responsive.bootstrap4.min.css')  }}" rel="stylesheet" type="text/css" />
<!-- Multi Item Selection examples -->
<link href="{{ asset('assets/plugins/datatables/select.bootstrap4.min.css')  }}" rel="stylesheet" type="text/css" />

<!-- App css -->
<link href="{{ asset('assets/css/bootstrap.min.css')  }}" rel="stylesheet" type="text/css" />
<link href="{{ asset('assets/css/icons.css')  }}" rel="stylesheet" type="text/css" />
<link href="{{ asset('assets/css/style.css')  }}" rel="stylesheet" type="text/css" />
<link href="{{ asset('assets/plugins/sweet-alert/sweetalert2.min.css')  }}" rel="stylesheet" type="text/css" />

<script src="{{ asset('assets/js/modernizr.min.js')  }}"></script>
@endpush

@push('style')
<style>
   .mtop-100 {
      margin-top: 150px !important;
   }

</style>
@endpush

@section('content')
<div class="row">
   <div class="col-12">
      <div class="card-box table-responsive">
         <table id="datatable" class="table table-bordered  m-t-30">
            <thead>
               <tr>
                  <th width="5%">No</th>
                  <th>Title</th>
                  <th width="10%">Status</th>
                  <th width="20%">Category</th>
                  <th width="20%">Tag</th>
                  <th width="15%">Action</th>
               </tr>
            </thead>
            <tbody>

            </tbody>
         </table>
      </div>
   </div>
   {{-- @include('backend.post.content._form') --}}
</div>
@endsection

@push('js')

<script src="{{ asset('assets/plugins/datatables/jquery.dataTables.min.js')  }}"></script>
<script src="{{ asset('assets/plugins/datatables/dataTables.bootstrap4.min.js')  }}"></script>
<!-- Buttons examples -->
<script src="{{ asset('assets/plugins/datatables/dataTables.buttons.min.js')  }}"></script>
<script src="{{ asset('assets/plugins/sweet-alert/sweetalert2.min.js')  }}"></script>
<script src="{{ asset('assets/pages/jquery.sweet-alert.init.js')  }}"></script>
{{-- sweat allert  --}}

<!-- Responsive examples -->
<script src="{{ asset('assets/plugins/datatables/dataTables.responsive.min.js')  }}"></script>
<script src="{{ asset('assets/plugins/datatables/responsive.bootstrap4.min.js')  }}"></script>

<!-- Selection table -->
<script src="{{ asset('assets/plugins/datatables/dataTables.select.min.js')  }}"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
@endpush

@push('script')

@include('backend.crud.js')
<script>

   
   let dataTable = $('#datatable').DataTable({
      dom: 'lBfrtip',
      buttons: [{
         className: 'btn btn-success btn-sm mr-2',
         text: 'Create',
         action: function (e, dt, node, config) {
            window.location = "{{ route('backend.post.content.create') }}";
         }
      }, {
         className: 'btn btn-warning btn-sm mr-2',
         text: 'Reload',
         action: function (e, dt, node, config) {
            reloadDatatable();
            Toast.fire({
               icon: 'success',
               title: 'Reload'
            })
         }
      }],
      responsive: true,
      processing: true,
      serverSide: true,
      searching: true,
      pageLength: 5,
      lengthMenu: [
         [5, 10, 15, -1],
         [5, 10, 15, "All"]
      ],
      ajax: {
         url: child_url,
         type: 'GET',
      },
      columns: [{
            data: 'DT_RowIndex',
            orderable: false
         },
         {
            data: 'title',
            orderable: true
         },
         {
            data: 'status',
            orderable: true
         },
         {
            data: 'category',
            orderable: true
         },

         {
            data: 'tag',
            orderable: true
         },
         {
            data: 'action',
            name: '#',
            orderable: false
         },
      ]
   });

   function deleteItem(id) {
      deleteConfirm(id)

   }
   function reloadDatatable() {
      dataTable.ajax.reload();
   }

   function editItem(id) {
      window.location = "/admin/post/content/"+id+"/edit";
   }

</script>




@endpush