routes/web.php
<?php

use App\Models\Content;
use Illuminate\Support\Facades\Route;



Auth::routes();



Route::group([
   'prefix' => 'admin',
   'as' => 'backend.',
   'middleware' => 'auth',
], function () {
   Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
   Route::get('/dashboard', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
   Route::resource('timeline', App\Http\Controllers\Backend\TimelineController::class);

   //POST ROUTE
   Route::group([
      'prefix' => 'post',
      'as' => 'post.',
   ], function () {
      Route::resource('content', App\Http\Controllers\Backend\Post\ContentController::class);
      Route::get('content/getimage/{id}', [App\Http\Controllers\Backend\Post\ContentController::class, 'getImage']);
      Route::post('content/addimage', [App\Http\Controllers\Backend\Post\ContentController::class, 'addImage'])->name('addimage');
      Route::delete('content/deleteimage/{id}', [App\Http\Controllers\Backend\Post\ContentController::class, 'deleteImage'])->name('deleteimage');
      Route::post('content/edit/editimage', [App\Http\Controllers\Backend\Post\ContentController::class, 'editImage'])->name('editimage');
      Route::resource('category', App\Http\Controllers\Backend\Post\CategoryController::class);
      Route::resource('tag', App\Http\Controllers\Backend\Post\TagController::class);
   });

   Route::resource('slider', App\Http\Controllers\Backend\SliderController::class);
   //about
   Route::group([
      'prefix' => 'about',
      'as' => 'about.',
   ], function () {
      Route::resource('structure', App\Http\Controllers\Backend\About\StructureController::class);
      Route::resource('contact', App\Http\Controllers\Backend\About\ContactController::class);


      Route::resource('member', App\Http\Controllers\Backend\About\MemberController::class);
   });
});

app/Http/Controllers/Backend/About/ContactController.php
<?php

namespace App\Http\Controllers\Backend\About;

use App\Models\File;
use App\Http\Controllers\Controller;
use App\Models\Contact;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Yajra\DataTables\Facades\DataTables;
use Str;
use Intervention\Image\Facades\Image;

class ContactController extends Controller
{
   /**
    * Display a listing of the resource.
    *
    * @return \Illuminate\Http\Response
    */
   public function index(Request $request)
   {
      if ($request->ajax()) {
         $contacts = Contact::latest()->get();
         return DataTables::of($contacts)
            ->addColumn('image', function ($contact) {
               return '
             <img height="200px" src="' . asset("storage/" . $contact->files->first()->link) . '">
                      ';
            })
            ->addColumn('action', function ($contact) {
               return '
                           <a class="btn btn-danger btn-sm"  onclick="deleteItem(' . $contact->id . ')"><i class="fa fa-trash"></i></span></a>
                           <a class="btn btn-info btn-sm" onclick="editItem(' . $contact->id . ')"><i class="fa fa-pencil"></i></span></a>
                           ';
            })
            ->removeColumn('id')
            ->addIndexColumn()
            ->rawColumns(['action', 'image'])
            ->make(true);
      }
      $data['title'] = "CONTACT";
      return view('backend.about.contact.index', $data);
   }

   /**
    * Show the form for creating a new resource.
    *
    * @return \Illuminate\Http\Response
    */
   public function create()
   {
      //
   }

   /**
    * Store a newly created resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @return \Illuminate\Http\Response
    */
   public function store(Request $request)
   {
      $path = null;
      $contact = new Contact();
      $contact->name = $request->name;
      $contact->description = $request->description;
      $contact->save();
      if ($request->file('file')) {
         $name_picture = Str::random(6) . '.png';
         $picture = Image::make($request['file'])->resize(null, 300, function ($constraint) {
            $constraint->aspectRatio();
            $constraint->upsize();
         })->encode('png', 100);
         $namePath = "contacs";
         $path = $namePath . "/" . $name_picture;

         Storage::put("public/" . $path, $picture);
      }
      if ($path != null) {
         $contact->files()->create(['link' => $path, 'type' => 'image']);
      }
      return $contact;
   }

   /**
    * Display the specified resource.
    *
    * @param  \App\Models\Contact  $contact
    * @return \Illuminate\Http\Response
    */
   public function show(Contact $contact)
   {
      //
   }

   /**
    * Show the form for editing the specified resource.
    *
    * @param  \App\Models\Contact  $contact
    * @return \Illuminate\Http\Response
    */
   public function edit(Contact $contact)
   {


      return $contact;
   }

   /**
    * Update the specified resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @param  \App\Models\Contact  $contact
    * @return \Illuminate\Http\Response
    */
   public function update(Request $request, Contact $contact)
   {
      $path = null;
      $contact->name = $request->name;
      $contact->description = $request->description;
      $contact->save();

      if ($request->file('file')) {
         if (count($contact->files) > 0) {
            if (Storage::exists("public/" . $contact->files->first()->link)) {
               Storage::delete("public/" . $contact->files->first()->link);
               $contact->files->first()->delete();
            }
         }




         $name_picture = Str::random(6) . '.png';
         $picture = Image::make($request['file'])->resize(null, 300, function ($constraint) {
            $constraint->aspectRatio();
            $constraint->upsize();
         })->encode('png', 100);
         $namePath = "contacs";
         $path = $namePath . "/" . $name_picture;




         Storage::put("public/" . $path, $picture);

         $contact->files()->create(['link' => $path, 'type' => 'image']);
      }



      return $contact;
   }

   /**
    * Remove the specified resource from storage.
    *
    * @param  \App\Models\Contact  $contact
    * @return \Illuminate\Http\Response
    */
   public function destroy(Contact $contact)
   {
      if (count($contact->files) > 0) {
         $id = $contact->files->first()->id;
         $img = File::find($id);
         if (Storage::exists("public/" . $img->link)) {
            Storage::delete("public/" . $img->link);
            $img->delete();
         }
      }
      $contact->delete();
      return response()->json(['message', 'deleted success']);
   }
}

app/Http/Controllers/Backend/About/MemberController.php
<?php

namespace App\Http\Controllers\Backend\About;

use App\Http\Controllers\Controller;
use App\Models\File;
use App\Models\Member;
use App\Models\Structure;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Yajra\DataTables\Facades\DataTables;
use Str;
use Intervention\Image\Facades\Image;

class MemberController extends Controller
{
   /**
    * Display a listing of the resource.
    *
    * @return \Illuminate\Http\Response
    */
   public function index(Request $request)
   {
      $lastyear = Structure::latest()->get();
      if ($request->ajax()) {
         if ($request->year != null) {
            $year = intval($request->year);

            $members = Member::where('priod', $year)->get();
         } else {
            $latestyear = Structure::orderBy('year', 'desc')->first();
            $members = Member::where('priod', $latestyear->year)->get();
         }

         return DataTables::of($members)
            ->addColumn('image', function ($member) {
               if (count($member->files) > 0) {
                  return '
            <img height="200px" src="' . asset('storage/' . $member->files->first()->link) . '">
                     ';
               } else {
                  return '';
               }
            })
            ->addColumn('struc', function ($member) {
               return $member->structure->name;
            })


            ->addColumn('action', function ($member) {
               return '

                          <a class="btn btn-danger btn-sm"  onclick="deleteItem(' . $member->id . ')"><i class="fa fa-trash"></i></span></a>
                          <a class="btn btn-info btn-sm" onclick="editItem(' . $member->id . ')"><i class="fa fa-pencil"></i></span></a>
                          ';
            })

            ->removeColumn('id')
            ->addIndexColumn()
            ->rawColumns(['action', 'image'])
            ->make(true);
      }
      $data['title'] = "ANGGOTA";
      $latestyear = Structure::orderBy('year', 'desc')->first();
      $data['structure'] = Structure::orderBy('year', 'desc')->get();


      $data['year'] = Structure::all()->unique('year')->sortByDesc('year');

      return view('backend.about.member.index', $data);
   }

   /**
    * Show the form for creating a new resource.
    *
    * @return \Illuminate\Http\Response
    */
   public function create()
   {
      //
   }

   /**
    * Store a newly created resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @return \Illuminate\Http\Response
    */
   public function store(Request $request)
   {
      $path = null;
      $member = new Member();
      $member->name = $request->name;
      $member->nim = $request->nim;
      $member->year = $request->year;
      $member->address = $request->address;
      $member->grade = $request->grade;
      $member->majors = $request->majors;
      $member->priod = Structure::find($request->structure_id)->year;
      $member->structure_id = $request->structure_id;

      $member->save();
      if ($request->file('image')) {
         $name_picture = Str::random(6) . '.png';
         $picture = Image::make($request['image'])->resize(null, 300, function ($constraint) {
            $constraint->aspectRatio();
            $constraint->upsize();
         })->encode('png', 100);
         $namePath = "members";
         $path = $namePath . "/" . $name_picture;

         Storage::put("public/" . $path, $picture);
         // dd(Storage::exists($content->images));
      }
      if ($path != null) {
         $member->files()->create(['link' => $path, 'type' => 'image']);
      }
      //   dd($content->files);
      return $member;
   }

   /**
    * Display the specified resource.
    *
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
   public function show($id)
   {
      //
   }

   /**
    * Show the form for editing the specified resource.
    *
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
   public function edit($id)
   {
      $member = Member::where('id', $id)->first();

      return $member;
   }

   /**
    * Update the specified resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
   public function update(Request $request, Member $member)
   {
      $path = null;

      $member->name = $request->name;
      $member->nim = $request->nim;
      $member->year = $request->year;
      $member->address = $request->address;
      $member->grade = $request->grade;
      $member->majors = $request->majors;
      $member->priod = Structure::find($request->structure_id)->year;
      $member->structure_id = $request->structure_id;
      $member->save();

      if ($request->file('image')) {
         if (count($member->files) > 0) {
            if (Storage::exists("public/" . $member->files->first()->link)) {
               Storage::delete("public/" . $member->files->first()->link);
               $member->files->first()->delete();
            }
         }




         $name_picture = Str::random(6) . '.png';
         $picture = Image::make($request['image'])->resize(null, 300, function ($constraint) {
            $constraint->aspectRatio();
            $constraint->upsize();
         })->encode('png', 100);
         $namePath = "members";
         $path = $namePath . "/" . $name_picture;




         Storage::put("public/" . $path, $picture);

         $member->files()->create(['link' => $path, 'type' => 'image']);
         // dd($member->files);
         // dd(Storage::exists($content->images));
      }



      return $member;
   }

   /**
    * Remove the specified resource from storage.
    *
    * @param  int  $id
    * @return \Illuminate\Http\Response
    */
   public function destroy(Member $member)
   {

      if (count($member->files) > 0) {
         $id = $member->files->first()->id;


         $img = File::find($id);

         if (Storage::exists("public/" . $img->link)) {
            Storage::delete("public/" . $img->link);
            $img->delete();
         }
      }


      $member->delete();
      return response()->json(['message', 'deleted success']);
   }
}

app/Http/Controllers/Backend/Post/CategoryController.php
<?php

namespace App\Http\Controllers\Backend\Post;

use App\Http\Controllers\Controller;
use App\Models\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Yajra\DataTables\Facades\DataTables;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

        if ($request->ajax()) {
            $categories = Category::latest()->get();
            return DataTables::of($categories)
                ->addColumn('action', function ($category) {
                    return '
                             <a class="btn btn-danger btn-sm"  onclick="deleteItem(' . $category->id . ')"><i class="fa fa-trash"></i></span></a>
                             <a class="btn btn-info btn-sm" onclick="editItem(' . $category->id . ')"><i class="fa fa-pencil"></i></span></a>
                             ';
                })
                ->removeColumn('id')
                ->addIndexColumn()
                ->rawColumns(['action'])
                ->make(true);
        }
        $data['title'] = "CATEGORY";
        return view('backend.post.category.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $category = new Category();
        $category->name = $request->name;
        $category->slug = Str::of($request->name)->slug('-');
        // dd($category->slug);
        $category->save();
        return $category;

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return $category;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {

        $category->update($request->all());
        $category->slug = Str::of($request->name)->slug('-');
        $category->save();
        return $category;

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $category->delete();
        return response()->json(['message', 'deleted success']);

    }
}

resources/views/layouts/partial/backend/sidebar.blade.php
<div class="left side-menu">
    <div class="sidebar-inner slimscrollleft">

        <!-- User -->

        <!-- End User -->

        <!--- Sidemenu -->
        <div id="sidebar-menu">
            <ul>
                <li class="text-muted menu-title">Navigation</li>

                <li>
                    <a href="{{ route('backend.home') }}" class="waves-effect"><i class="mdi mdi-view-dashboard"></i>
                        <span> Dashboard </span> </a>
                </li>
                <li class="has_sub">
                    <a href="javascript:void(0);" class="waves-effect "><i class="mdi mdi-invert-colors"></i> <span>
                            Posts</span> <span class="menu-arrow"></span></a>
                    <ul class="list-unstyled">
                        <li><a href="{{ route('backend.post.content.index') }}">Content</a></li>
                        <li><a href="{{ route('backend.post.tag.index') }}">Tags</a></li>
                        <li><a href="{{ route('backend.post.category.index') }}">Categories</a></li>
                        {{-- <li><a href="form-wizard.html">Galeries</a></li> --}}

                    </ul>
                </li>
                <li>
                    <a href="{{ route('backend.slider.index') }}" class="waves-effect"><i
                            class="mdi mdi-invert-colors"></i> <span>Slider</span></span></a>
                </li>
                <li>
                    <a href="{{ route('backend.timeline.index') }}" class="waves-effect"><i
                            class="mdi mdi-invert-colors"></i> <span>Timeline</span></span></a>
                </li>

                <li class="has_sub">
                    <a href="javascript:void(0);" class="waves-effect"><i class="mdi mdi-invert-colors"></i>
                        <span>Tentang HIMASTER</span></a>
                    <ul class="list-unstyled">
                        <li><a href="{{ route('backend.about.member.index') }}">Anggota</a></li>
                        <li><a href="{{ route('backend.about.structure.index') }}">Komponen</a></li>
                        <li><a href="{{ route('backend.about.contact.index') }}">Kontak</a></li>
                    </ul>
                </li>

                <li>

                    <a href="{{ route('logout') }}" onclick="event.preventDefault();
                                    document.getElementById('logout-form').submit();">
                        <i class="fa fa-sign-out"></i><span> Logout </span>
                    </a>


                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                        @csrf
                    </form>
                </li>

                {{-- <li class="has_sub">
               <a href="javascript:void(0);" class="waves-effect"><i class="mdi mdi-texture"></i><span class="badge badge-warning pull-right">7</span><span> Forms </span> </a>
               <ul class="list-unstyled">
                  <li><a href="form-elements.html">Articles</a></li>
                  <li><a href="form-advanced.html">Categories</a></li>
                  <li><a href="form-validation.html">Tags</a></li>
                  <li><a href="form-wizard.html">Galeries</a></li>

               </ul>
            </li> --}}



            </ul>
            <div class="clearfix"></div>
        </div>
        <!-- Sidebar -->
        <div class="clearfix"></div>

    </div>

</div><!-- end navbar-custom -->

resources/views/layouts/partial/backend/topbar.blade.php
<div class="topbar">

    <!-- LOGO -->
    <div class="topbar-left">
        <a href="index.html" class="logo"><span style="color: black; font-size: 20px">HIMASTER</span></i></a>
    </div>

    <!-- Button mobile view to collapse sidebar menu -->
    <div class="navbar navbar-default" role="navigation">
        <div class="container-fluid">

            <!-- Page title -->
            <ul class="nav navbar-nav list-inline navbar-left">
                <li class="list-inline-item">
                    <button class="button-menu-mobile open-left">
                        <i class="mdi mdi-menu"></i>
                    </button>
                </li>
                <li class="list-inline-item">
                    <h4 class="page-title">{{ $title }}</h4>
                </li>
            </ul>

            <nav class="navbar-custom">

                <ul class="list-unstyled topbar-right-menu float-right mb-0">

                    <li>
                        <!-- Notification -->
                        <div class="notification-box">
                            <ul class="list-inline mb-0">
                                <li>
                                    <a href="javascript:void(0);" class="right-bar-toggle">
                                        <i class="mdi mdi-bell-outline noti-icon"></i>
                                    </a>
                                    <div class="noti-dot">
                                        <span class="dot"></span>
                                        <span class="pulse"></span>
                                    </div>
                                </li>
                            </ul>
                        </div>
                        <!-- End Notification bar -->
                    </li>

                    <li class="hide-phone">
                        <form class="app-search">
                            <input type="text" placeholder="Search..." class="form-control">
                            <button type="submit"><i class="fa fa-search"></i></button>
                        </form>
                    </li>

                </ul>
            </nav>
        </div><!-- end container -->
    </div><!-- end navbar -->
</div>